name: SSH deploy on push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: .
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
          remote_key_pass: ${{ secrets.REMOTE_KEY_PASS }}
          remote_path: ${{ secrets.REMOTE_PATH }}

      - name: SSH into server and set up Laravel
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          passphrase: ${{ secrets.REMOTE_KEY_PASS }}
          script: |
            cd ${{ secrets.REMOTE_PATH }}
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan storage:link
            chmod -R 775 storage bootstrap/cache
            chown -R www-data:www-data storage bootstrap/cache
            php artisan queue:restart
